// Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	.file	"c:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_ia64/blottorch.c"
	.radix	D
	.section	.text,	"ax", "progbits"
	.align 32
	.section	.pdata,	"a", "progbits"
	.align 4
	.section	.xdata,	"a", "progbits"
	.align 8
	.section	.text$zz,	"ax", "progbits"
	.align 16
	.section	.pdata,	"a", "progbits"
	.align 4
	.section	.text$zy,	"ax", "progbits"
	.align 16
	.section	.pdata,	"a", "progbits"
	.align 4
	.section	.data,	"wa", "progbits"
	.align 16
	.section	.rdata,	"a", "progbits"
	.align 16
	.section	.bss,	"wa", "nobits"
	.align 16
	.section	.debug$S,	"ax", "progbits"
	.align 16
	.section	$$TYPES,	"ax", "progbits"
	.align 16
	.section	.tls$,	"was", "progbits"
	.align 16
	.section	.sdata,	"was", "progbits"
	.align 16
	.section	.sbss,	"was", "nobits"
	.align 16
	.section	.srdata,	"as", "progbits"
	.align 16
	.section	.rdata,	"a", "progbits"
	.align 16
	.section	.data
$SG3945: string	"/sys/class/thermal/thermal_zone1/temp\000"
	.skip 10
$SG3947: string	"/sys/class/thermal/thermal_zone2/temp\000"
	.skip 10
$SG3949: string	"/sys/class/thermal/thermal_zone7/temp\000"
	.skip 10
$SG3952: string	"Error opening temperature file\000"
	.skip 1
$SG3955: string	"Error opening temperature file\000"
	.skip 1
$SG3958: string	"Error opening temperature file\000"
	.skip 1
$SG3961: string	"Error reading temperature data\n\000"
$SG3964: string	"Error reading temperature data\n\000"
$SG3967: string	"Error reading temperature data\n\000"
$SG3968: string	"########################################################"
	string	"######################\n\n\000"
	.skip 15
$SG3969: string	"    New York Lottery v7.0 by alCoPaUL [NaCl][GIMO][ZnI]["
	string	"b8]  June 11, 2026    \n\n\000"
	.skip 15
$SG3970: string	"########################################################"
	string	"######################\n\n\000"
	.skip 15
$SG3979: string	"MegaMillions\n\n\000"
	.skip 1
$SG3981: string	"PowerBall\n\n\000"
	.skip 4
$SG3983: string	"NY Lotto 1\n\000"
	.skip 4
$SG3984: string	"NY Lotto 2\n\n\000"
	.skip 3
$SG3986: string	"Cash4Life\n\n\000"
	.skip 4
$SG3988: string	"Take 5\n\n\000"
	.skip 7
$SG3990: string	"Pick 10\n\n\000"
	.skip 6
$SG3999: string	"[Midday] || \000"
	.skip 3
$SG4001: string	"[Evening] = Numbers\n\n\000"
	.skip 10
$SG4003: string	"[Midday] || \000"
	.skip 3
$SG4005: string	"[Evening] = Win 4\n\n\000"
	.skip 12
$SG4006: string	"QuickDraw\n\n\000"
	.skip 4
$SG4007: string	"########################################################"
	string	"######################\n\n\000"
	.section	.sdata
$SG3948: string	"r\000"
$SG3946: string	"r\000"
$SG3944: string	"r\000"
	.skip 2
$SG3966: string	"%f\000"
	.skip 1
$SG3963: string	"%f\000"
	.skip 1
$SG3960: string	"%f\000"
	.skip 5
$SG3930: string	"%d = \000"
	.skip 2
$SG3917: string	"%d = \000"
	.skip 2
$SG3931: string	"%d+ = \000"
	.skip 1
$SG3919: string	"%d+ = \000"
	.type	main#	,@function 
        .global main#
	.type	getchar#	,@function 
        .global getchar#
	.type	srand#	,@function 
        .global srand#
	.type	printf#	,@function 
        .global printf#
	.type	fclose#	,@function 
        .global fclose#
	.type	fprintf#	,@function 
        .global fprintf#
	.type	__iob_func#	,@function 
        .global __iob_func#
	.type	fscanf#	,@function 
        .global fscanf#
	.type	perror#	,@function 
        .global perror#
	.type	fopen#	,@function 
        .global fopen#
	.type	_fltused#	,@object 
        .global _fltused#
	.section	.pdata
$T4032:	data4	@imagerel($LN31@main#)
	data4	@imagerel($LN31@main#+4048)
	data4	@imagerel($T4030#)
	.section	.xdata
$T4030:	data2	03H
	data2	00H
	data4	03H
	string	"\x05"		//R1:prologue size 5
	string	"\xe6\x00"	//P7:pfs_when time 0
	string	"\xb1\x21"	//P3:pfs_gr 33
	string	"\xe0\x01\x0a"	//P7:mem_stack_f time 1 size 10
	string	"\xe4\x02"	//P7:rp_when time 2
	string	"\xb0\xa0"	//P3:rp_gr 32
	string	"\x61\xf2\x05"	//R3:body size 754
	string	"\x81"		//B1:label_state 1
	string	"\xc0\x05"	//B2:ecount 0 time 5
	string	"\x00\x00\x00\x00\x00\x00" //padding
// Function compile flags: /Odtp
	.section	.text

// Begin code for function: main:
	.proc	main#
	.align 32
fp2$	= 16
i$	= 24
fp$	= 32
ia$	= 40
fp1$	= 48
temp_milli$	= 56
rawtime$	= 64
temp_milli2$	= 72
temp_milli1$	= 76
timeinfo$	= 80
$T4015	= 88
$T4016	= 96
$T4017	= 104
$T4018	= 112
$T4019	= 120
$T4020	= 128
$T4021	= 136
$T4022	= 144
$T4023	= 152
$T4024	= 160
$T4025	= 168
$T4026	= 172
main: 
// Output regs: r35-r38
// File c:\program files (x86)\microsoft visual studio 10.0\vc\bin\x86_ia64\blottorch.c
$LN31@main:
 {   .mmi  //R-Addr: 0X00 
	alloc	r33=0, 3, 4, 0				    //72 	cc:0
	adds	sp=-160, sp				    //72 	cc:0, ffffff60H
	mov	r32=b0					    //72 	cc:0
 }
 {   .mmi  //R-Addr: 0X010 
	mov	r34=gp;;				    //72 	cc:0
	ld8.nta	r2=[sp]					    //72 	cc:1
	nop.i	 0;;
 }
 {   .mib  //R-Addr: 0X020 
	addl	r31=@ltoff($SG3945#),gp			    //83 	cc:0
	addl	r36=@gprel($SG3944#),gp			    //83 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X030 
	ld8	r35=[r31]				    //83 	cc:1
	nop.m	 0
	br.call.sptk.few b0=fopen#;;			    //83 	cc:1
 }
 {   .mmi  //R-Addr: 0X040 
	adds	r30=$T4015, sp				    //83 	cc:12
	adds	r29=$T4015, sp				    //83 	cc:12
	adds	r27=fp2$, sp				    //83 	cc:12
 }
 {   .mmi  //R-Addr: 0X050 
	mov	gp=r34;;				    //83 	cc:12
	st8	[r30]=r8				    //83 	cc:13
	nop.i	 0
 }
 {   .mmi  //R-Addr: 0X060 
	ld8	r28=[r29];;				    //83 	cc:13
	st8	[r27]=r28				    //83 	cc:14
	nop.i	 0;;
 }
 {   .mib  //R-Addr: 0X070 
	addl	r26=@ltoff($SG3947#),gp			    //84 	cc:0
	addl	r36=@gprel($SG3946#),gp			    //84 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X080 
	ld8	r35=[r26]				    //84 	cc:1
	nop.m	 0
	br.call.sptk.few b0=fopen#;;			    //84 	cc:1
 }
 {   .mmi  //R-Addr: 0X090 
	adds	r25=$T4016, sp				    //84 	cc:12
	adds	r22=$T4016, sp				    //84 	cc:12
	adds	r20=fp1$, sp				    //84 	cc:12
 }
 {   .mmi  //R-Addr: 0X0a0 
	mov	gp=r34;;				    //84 	cc:12
	st8	[r25]=r8				    //84 	cc:13
	nop.i	 0
 }
 {   .mmi  //R-Addr: 0X0b0 
	ld8	r21=[r22];;				    //84 	cc:13
	st8	[r20]=r21				    //84 	cc:14
	nop.i	 0;;
 }
 {   .mib  //R-Addr: 0X0c0 
	addl	r19=@ltoff($SG3949#),gp			    //85 	cc:0
	addl	r36=@gprel($SG3948#),gp			    //85 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0d0 
	ld8	r35=[r19]				    //85 	cc:1
	nop.m	 0
	br.call.sptk.few b0=fopen#;;			    //85 	cc:1
 }
 {   .mmi  //R-Addr: 0X0e0 
	adds	r18=$T4017, sp				    //85 	cc:12
	adds	r17=$T4017, sp				    //85 	cc:12
	adds	r15=fp$, sp				    //85 	cc:12
 }
 {   .mmi  //R-Addr: 0X0f0 
	mov	gp=r34;;				    //85 	cc:12
	st8	[r18]=r8				    //85 	cc:13
	nop.i	 0
 }
 {   .mmi  //R-Addr: 0X0100 
	ld8	r16=[r17];;				    //85 	cc:13
	st8	[r15]=r16				    //85 	cc:14
	nop.i	 0;;
 }
 {   .mmi  //R-Addr: 0X0110 
	adds	r11=fp2$, sp;;				    //86 	cc:0
	ld8	r10=[r11]				    //86 	cc:1
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0120 
	cmp.ne.unc p14,p15=r0, r10			    //86 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN26@main#;;			    //86 	cc:2
 }
 {   .mmi  //R-Addr: 0X0130 
	addl	r9=@ltoff($SG3952#),gp;;		    //86 	cc:3
	ld8	r35=[r9]				    //86 	cc:4
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0140 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=perror#;;			    //86 	cc:4
 }
 {   .mib  //R-Addr: 0X0150 
	mov	gp=r34					    //86 	cc:15
	mov	r8=1					    //86 	cc:15
	br.cond.sptk.few $LN27@main#;;			    //86 	cc:15
 }
$LN26@main:
 {   .mmi  //R-Addr: 0X0160 
	adds	r8=fp1$, sp;;				    //87 	cc:0
	ld8	r31=[r8]				    //87 	cc:1
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0170 
	cmp.ne.unc p14,p15=r0, r31			    //87 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN25@main#;;			    //87 	cc:2
 }
 {   .mmi  //R-Addr: 0X0180 
	addl	r30=@ltoff($SG3955#),gp;;		    //87 	cc:3
	ld8	r35=[r30]				    //87 	cc:4
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0190 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=perror#;;			    //87 	cc:4
 }
 {   .mib  //R-Addr: 0X01a0 
	mov	gp=r34					    //87 	cc:15
	mov	r8=1					    //87 	cc:15
	br.cond.sptk.few $LN27@main#;;			    //87 	cc:15
 }
$LN25@main:
 {   .mmi  //R-Addr: 0X01b0 
	adds	r29=fp$, sp;;				    //88 	cc:0
	ld8	r28=[r29]				    //88 	cc:1
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X01c0 
	cmp.ne.unc p14,p15=r0, r28			    //88 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN24@main#;;			    //88 	cc:2
 }
 {   .mmi  //R-Addr: 0X01d0 
	addl	r27=@ltoff($SG3958#),gp;;		    //88 	cc:3
	ld8	r35=[r27]				    //88 	cc:4
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X01e0 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=perror#;;			    //88 	cc:4
 }
 {   .mib  //R-Addr: 0X01f0 
	mov	gp=r34					    //88 	cc:15
	mov	r8=1					    //88 	cc:15
	br.cond.sptk.few $LN27@main#;;			    //88 	cc:15
 }
$LN24@main:
 {   .mmi  //R-Addr: 0X0200 
	addl	r36=@gprel($SG3960#),gp			    //90 	cc:0
	adds	r26=fp2$, sp				    //90 	cc:0
	adds	r37=temp_milli2$, sp;;			    //90 	cc:0
 }
 {   .mmb  //R-Addr: 0X0210 
	ld8	r35=[r26]				    //90 	cc:1
	nop.m	 0
	br.call.sptk.few b0=fscanf#;;			    //90 	cc:1
 }
 {   .mmi  //R-Addr: 0X0220 
	adds	r25=$T4018, sp				    //90 	cc:12
	adds	r22=$T4018, sp				    //90 	cc:12
	mov	gp=r34;;				    //90 	cc:12
 }
 {   .mmb  //R-Addr: 0X0230 
	st4	[r25]=r8				    //90 	cc:13
	ld4	r21=[r22]				    //90 	cc:13
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0240 
	cmp4.eq.unc p14,p15=1, r21			    //90 	cc:14
	nop.m	 0
  (p14)	br.cond.dptk.few $LN23@main#;;			    //90 	cc:14
 }
 {   .mmb  //R-Addr: 0X0250 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=__iob_func#;;		    //90 	cc:15
 }
 {   .mmi  //R-Addr: 0X0260 
	mov	gp=r34					    //90 	cc:26
	adds	r20=$T4019, sp				    //90 	cc:26
	adds	r18=$T4019, sp;;			    //90 	cc:26
 }
 {   .mmi  //R-Addr: 0X0270 
	st8	[r20]=r8				    //90 	cc:27
	ld8	r17=[r18]				    //90 	cc:27
	addl	r19=@ltoff($SG3961#),gp;;		    //90 	cc:27
 }
 {   .mib  //R-Addr: 0X0280 
	ld8	r36=[r19]				    //90 	cc:28
	adds	r35=96, r17				    //90 	cc:28, 00000060H
	br.call.sptk.few b0=fprintf#;;			    //90 	cc:28
 }
 {   .mib  //R-Addr: 0X0290 
	adds	r16=fp2$, sp				    //90 	cc:39
	mov	gp=r34					    //90 	cc:39
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X02a0 
	ld8	r35=[r16]				    //90 	cc:40
	nop.m	 0
	br.call.sptk.few b0=fclose#;;			    //90 	cc:40
 }
 {   .mib  //R-Addr: 0X02b0 
	mov	gp=r34					    //90 	cc:51
	mov	r8=1					    //90 	cc:51
	br.cond.sptk.few $LN27@main#;;			    //90 	cc:51
 }
$LN23@main:
 {   .mmi  //R-Addr: 0X02c0 
	addl	r36=@gprel($SG3963#),gp			    //91 	cc:0
	adds	r15=fp1$, sp				    //91 	cc:0
	adds	r37=temp_milli1$, sp;;			    //91 	cc:0
 }
 {   .mmb  //R-Addr: 0X02d0 
	ld8	r35=[r15]				    //91 	cc:1
	nop.m	 0
	br.call.sptk.few b0=fscanf#;;			    //91 	cc:1
 }
 {   .mmi  //R-Addr: 0X02e0 
	adds	r11=$T4020, sp				    //91 	cc:12
	adds	r10=$T4020, sp				    //91 	cc:12
	mov	gp=r34;;				    //91 	cc:12
 }
 {   .mmb  //R-Addr: 0X02f0 
	st4	[r11]=r8				    //91 	cc:13
	ld4	r9=[r10]				    //91 	cc:13
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0300 
	cmp4.eq.unc p14,p15=1, r9			    //91 	cc:14
	nop.m	 0
  (p14)	br.cond.dptk.few $LN22@main#;;			    //91 	cc:14
 }
 {   .mmb  //R-Addr: 0X0310 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=__iob_func#;;		    //91 	cc:15
 }
 {   .mmi  //R-Addr: 0X0320 
	mov	gp=r34					    //91 	cc:26
	adds	r31=$T4021, sp				    //91 	cc:26
	adds	r29=$T4021, sp;;			    //91 	cc:26
 }
 {   .mmi  //R-Addr: 0X0330 
	st8	[r31]=r8				    //91 	cc:27
	ld8	r28=[r29]				    //91 	cc:27
	addl	r30=@ltoff($SG3964#),gp;;		    //91 	cc:27
 }
 {   .mib  //R-Addr: 0X0340 
	ld8	r36=[r30]				    //91 	cc:28
	adds	r35=96, r28				    //91 	cc:28, 00000060H
	br.call.sptk.few b0=fprintf#;;			    //91 	cc:28
 }
 {   .mib  //R-Addr: 0X0350 
	adds	r27=fp1$, sp				    //91 	cc:39
	mov	gp=r34					    //91 	cc:39
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0360 
	ld8	r35=[r27]				    //91 	cc:40
	nop.m	 0
	br.call.sptk.few b0=fclose#;;			    //91 	cc:40
 }
 {   .mib  //R-Addr: 0X0370 
	mov	gp=r34					    //91 	cc:51
	mov	r8=1					    //91 	cc:51
	br.cond.sptk.few $LN27@main#;;			    //91 	cc:51
 }
$LN22@main:
 {   .mmi  //R-Addr: 0X0380 
	addl	r36=@gprel($SG3966#),gp			    //92 	cc:0
	adds	r26=fp$, sp				    //92 	cc:0
	adds	r37=temp_milli$, sp;;			    //92 	cc:0
 }
 {   .mmb  //R-Addr: 0X0390 
	ld8	r35=[r26]				    //92 	cc:1
	nop.m	 0
	br.call.sptk.few b0=fscanf#;;			    //92 	cc:1
 }
 {   .mmi  //R-Addr: 0X03a0 
	adds	r25=$T4022, sp				    //92 	cc:12
	adds	r22=$T4022, sp				    //92 	cc:12
	mov	gp=r34;;				    //92 	cc:12
 }
 {   .mmb  //R-Addr: 0X03b0 
	st4	[r25]=r8				    //92 	cc:13
	ld4	r21=[r22]				    //92 	cc:13
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X03c0 
	cmp4.eq.unc p14,p15=1, r21			    //92 	cc:14
	nop.m	 0
  (p14)	br.cond.dptk.few $LN21@main#;;			    //92 	cc:14
 }
 {   .mmb  //R-Addr: 0X03d0 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=__iob_func#;;		    //92 	cc:15
 }
 {   .mmi  //R-Addr: 0X03e0 
	mov	gp=r34					    //92 	cc:26
	adds	r20=$T4023, sp				    //92 	cc:26
	adds	r18=$T4023, sp;;			    //92 	cc:26
 }
 {   .mmi  //R-Addr: 0X03f0 
	st8	[r20]=r8				    //92 	cc:27
	ld8	r17=[r18]				    //92 	cc:27
	addl	r19=@ltoff($SG3967#),gp;;		    //92 	cc:27
 }
 {   .mib  //R-Addr: 0X0400 
	ld8	r36=[r19]				    //92 	cc:28
	adds	r35=96, r17				    //92 	cc:28, 00000060H
	br.call.sptk.few b0=fprintf#;;			    //92 	cc:28
 }
 {   .mib  //R-Addr: 0X0410 
	adds	r16=fp$, sp				    //92 	cc:39
	mov	gp=r34					    //92 	cc:39
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0420 
	ld8	r35=[r16]				    //92 	cc:40
	nop.m	 0
	br.call.sptk.few b0=fclose#;;			    //92 	cc:40
 }
 {   .mib  //R-Addr: 0X0430 
	mov	gp=r34					    //92 	cc:51
	mov	r8=1					    //92 	cc:51
	br.cond.sptk.few $LN27@main#;;			    //92 	cc:51
 }
$LN21@main:
 {   .mmi  //R-Addr: 0X0440 
	adds	r15=fp2$, sp;;				    //93 	cc:0
	ld8	r35=[r15]				    //93 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0450 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=fclose#;;			    //93 	cc:1
 }
 {   .mmi  //R-Addr: 0X0460 
	mov	gp=r34;;				    //93 	cc:12
	adds	r11=fp1$, sp				    //94 	cc:0
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0470 
	ld8	r35=[r11]				    //94 	cc:1
	nop.m	 0
	br.call.sptk.few b0=fclose#;;			    //94 	cc:1
 }
 {   .mmi  //R-Addr: 0X0480 
	mov	gp=r34;;				    //94 	cc:12
	adds	r10=fp$, sp				    //95 	cc:0
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0490 
	ld8	r35=[r10]				    //95 	cc:1
	nop.m	 0
	br.call.sptk.few b0=fclose#;;			    //95 	cc:1
 }
 {   .mmb  //R-Addr: 0X04a0 
	mov	gp=r34					    //95 	cc:13
	adds	r35=rawtime$, sp			    //97 	cc:0
	br.call.sptk.few b0=time#;;			    //97 	cc:0
 }
 {   .mmb  //R-Addr: 0X04b0 
	adds	r35=rawtime$, sp			    //98 	cc:0
	nop.m	 0
	br.call.sptk.few b0=localtime#;;		    //98 	cc:0
 }
 {   .mib  //R-Addr: 0X04c0 
	adds	r9=$T4024, sp				    //98 	cc:11
	adds	r30=timeinfo$, sp			    //98 	cc:11
	nop.b	 0;;
 }
 {   .mib  //R-Addr: 0X04d0 
	st8	[r9]=r8					    //98 	cc:12
	adds	r8=$T4024, sp				    //98 	cc:12
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X04e0 
	ld8	r31=[r8];;				    //98 	cc:13
	st8	[r30]=r31				    //98 	cc:14
	nop.i	 0;;
 }
 {   .mmi  //R-Addr: 0X04f0 
	addl	r29=@ltoff($SG3968#),gp;;		    //100 	cc:0
	ld8	r35=[r29]				    //100 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0500 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //100 	cc:1
 }
 {   .mmi  //R-Addr: 0X0510 
	mov	gp=r34;;				    //100 	cc:12
	addl	r28=@ltoff($SG3969#),gp			    //101 	cc:0
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0520 
	ld8	r35=[r28]				    //101 	cc:1
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //101 	cc:1
 }
 {   .mmi  //R-Addr: 0X0530 
	mov	gp=r34;;				    //101 	cc:12
	addl	r27=@ltoff($SG3970#),gp			    //102 	cc:0
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0540 
	ld8	r35=[r27]				    //102 	cc:1
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //102 	cc:1
 }
 {   .mmi  //R-Addr: 0X0550 
	mov	gp=r34;;				    //102 	cc:12
	adds	r21=timeinfo$, sp			    //104 	cc:0
	mov	r17=1900				    //104 	cc:0, 0000076cH
 }
 {   .mmi  //R-Addr: 0X0560 
	mov	r15=65501				    //104 	cc:0, 0000ffddH
	adds	r26=timeinfo$, sp			    //104 	cc:0
	adds	r8=timeinfo$, sp;;			    //104 	cc:0
 }
 {   .mmi  //R-Addr: 0X0570 
	ld8	r20=[r21]				    //104 	cc:1
	ld8	r25=[r26]				    //104 	cc:1
	mov	r26=65501				    //104 	cc:1, 0000ffddH
 }
 {   .mmi  //R-Addr: 0X0580 
	setf.sig f6=r17					    //104 	cc:1
	setf.exp f8=r15					    //104 	cc:1
	adds	r17=temp_milli1$, sp;;			    //104 	cc:1
 }
 {   .mmi  //R-Addr: 0X0590 
	adds	r19=12, r20				    //104 	cc:2
	adds	r22=20, r25				    //104 	cc:2
	adds	r20=temp_milli2$, sp			    //104 	cc:2
 }
 {   .mib  //R-Addr: 0X05a0 
	setf.exp f12=r26				    //104 	cc:2
	adds	r15=temp_milli$, sp			    //104 	cc:2
	nop.b	 0;;
 }
 {   .mli  //R-Addr: 0X05b0 
	ld4	r18=[r19]				    //104 	cc:3
	movl	r19=4596373779694328218;;		    //104 	cc:3, 3fc999999999999aH
 }
 {   .mib  //R-Addr: 0X05c0 
	setf.d	f34=r19					    //104 	cc:4
	sxt4	r16=r18					    //104 	cc:4
	nop.b	 0
 }
 {   .mli  //R-Addr: 0X05d0 
	nop.m	 0
	movl	r18=4652007308841189376;;		    //104 	cc:4, 408f400000000000H
 }
 {   .mmi  //R-Addr: 0X05e0 
	setf.sig f7=r16					    //104 	cc:5
	setf.d	f36=r18					    //104 	cc:5
	cmp.eq.unc p15,p0=0, r16			    //104 	cc:5
 }
 {   .mli  //R-Addr: 0X05f0 
	nop.m	 0
	movl	r16=1115160576;;			    //104 	cc:5, 42780000H
 }
 {   .mmb  //R-Addr: 0X0600 
  (p15)	break.m	 1					    //104 	cc:6
	ld8	r31=[r8]				    //104 	cc:6
	nop.b	 0
 }
 {   .mmi  //R-Addr: 0X0610 
	setf.s	f43=r16;;				    //104 	cc:6
	ld4	r10=[r22]				    //104 	cc:7
	adds	r30=16, r31				    //104 	cc:7
 }
 {   .mfb  //R-Addr: 0X0620 
	nop.m	 0
	fcvt.xf	f6=f6					    //104 	cc:7
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0630 
	ld4	r29=[r30];;				    //104 	cc:8
	nop.m	 0
	sxt4	r27=r29;;				    //104 	cc:9
 }
 {   .mii  //R-Addr: 0X0640 
	setf.sig f11=r27				    //104 	cc:10
	cmp.eq.unc p15,p0=0, r27;;			    //104 	cc:10
  (p15)	break.i	 1					    //104 	cc:11
 }
 {   .mfb  //R-Addr: 0X0650 
	ldfs	f33=[r20]				    //104 	cc:11
	fcvt.xf	f7=f7					    //104 	cc:11
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0660 
	ldfs	f42=[r17]				    //104 	cc:12
	nop.m	 0
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0670 
	nop.m	 0
	frcpa.s1 f9,p6=f6, f7				    //104 	cc:15
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0680 
	nop.m	 0
	fcvt.xf	f11=f11					    //104 	cc:16
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0690 
	nop.m	 0
	fmpy.s0	f35=f33, f34				    //104 	cc:17
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X06a0 
	nop.m	 0
	fmpy.s0	f44=f42, f43				    //104 	cc:18
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X06b0 
	nop.m	 0
  (p6)	fma.s1	f6=f6, f9, f0				    //104 	cc:19
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X06c0 
	nop.m	 0
  (p6)	fnma.s1	f7=f7, f9, f1				    //104 	cc:19
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X06d0 
	nop.m	 0
	frcpa.s0 f37,p8=f35, f36			    //104 	cc:21
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X06e0 
	nop.m	 0
  (p6)	fma.s1	f6=f7, f6, f6				    //104 	cc:23
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X06f0 
	nop.m	 0
  (p6)	fma.s1	f7=f7, f7, f8				    //104 	cc:23
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0700 
	nop.m	 0
  (p8)	fma.s1	f38=f35, f37, f0			    //104 	cc:25
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0710 
	nop.m	 0
  (p8)	fnma.s1	f39=f36, f37, f1			    //104 	cc:25
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0720 
	nop.m	 0
  (p6)	fma.s1	f9=f7, f6, f6, f9			    //104 	cc:27
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0730 
	nop.m	 0
  (p8)	fma.s1	f38=f39, f38, f38			    //104 	cc:29
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0740 
	nop.m	 0
  (p8)	fma.s1	f40=f39, f39, f0			    //104 	cc:29
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0750 
	nop.m	 0
  (p8)	fma.s1	f37=f39, f37, f37			    //104 	cc:30
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0760 
	nop.m	 0
	fcvt.fx.trunc.s1 f6=f9, f6			    //104 	cc:31
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0770 
	nop.m	 0
  (p8)	fma.s1	f38=f40, f38, f38			    //104 	cc:33
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0780 
	nop.m	 0
  (p8)	fma.s1	f39=f40, f40, f0, f39			    //104 	cc:33
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0790 
	nop.m	 0
  (p8)	fma.s1	f37=f40, f37, f37			    //104 	cc:34
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X07a0 
	getf.sig r11=f6					    //104 	cc:35
	nop.m	 0
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X07b0 
	nop.m	 0
  (p8)	fma.d.s1 f38=f39, f38, f38			    //104 	cc:37
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X07c0 
	nop.m	 0
  (p8)	fma.s1	f37=f39, f37, f37			    //104 	cc:38
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X07d0 
	add	r9=r10, r11;;				    //104 	cc:40
	nop.m	 0
	sxt4	r28=r9					    //104 	cc:41
 }
 {   .mfb  //R-Addr: 0X07e0 
	nop.m	 0
  (p8)	fnma.d.s1 f40=f36, f38, f35, f40		    //104 	cc:41
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X07f0 
	setf.sig f10=r28				    //104 	cc:42
	nop.m	 0
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0800 
	nop.m	 0
  (p8)	fma.d.s0 f37=f40, f37, f38			    //104 	cc:45
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0810 
	nop.m	 0
	fcvt.xf	f10=f10					    //104 	cc:48
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0820 
	nop.m	 0
	frcpa.s1 f13,p7=f10, f11			    //104 	cc:52
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0830 
	nop.m	 0
  (p7)	fma.s1	f10=f10, f13, f0			    //104 	cc:56
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0840 
	nop.m	 0
  (p7)	fnma.s1	f11=f11, f13, f1			    //104 	cc:56
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0850 
	nop.m	 0
  (p7)	fma.s1	f10=f11, f10, f10			    //104 	cc:60
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0860 
	nop.m	 0
  (p7)	fma.s1	f11=f11, f11, f12			    //104 	cc:60
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0870 
	nop.m	 0
  (p7)	fma.s1	f13=f11, f10, f10, f13			    //104 	cc:64
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0880 
	nop.m	 0
	fcvt.fx.trunc.s1 f10=f13, f10			    //104 	cc:68
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0890 
	getf.sig r25=f10;;				    //104 	cc:72
	adds	r22=1, r25				    //104 	cc:77
	nop.i	 0;;
 }
 {   .mib  //R-Addr: 0X08a0 
	nop.m	 0
	sxt4	r21=r22					    //104 	cc:78
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X08b0 
	setf.sig f14=r21				    //104 	cc:79
	nop.m	 0
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X08c0 
	nop.m	 0
	fcvt.xf	f15=f14					    //104 	cc:85
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X08d0 
	nop.m	 0
	fnorm.d.s0 f32=f15				    //104 	cc:89
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X08e0 
	nop.m	 0
	fmpy.s0	f41=f32, f37				    //104 	cc:93
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X08f0 
	ldfs	f45=[r15]				    //104 	cc:0
	nop.m	 0
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0900 
	nop.m	 0
	frcpa.s0 f46,p9=f44, f45			    //104 	cc:6
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0910 
	nop.m	 0
  (p9)	fnma.s1	f48=f45, f46, f1			    //104 	cc:10
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0920 
	nop.m	 0
  (p9)	fma.s1	f47=f44, f46, f0			    //104 	cc:10
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0930 
	nop.m	 0
  (p9)	fma.s1	f47=f48, f47, f47			    //104 	cc:14
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0940 
	nop.m	 0
  (p9)	fma.s1	f48=f48, f48, f0			    //104 	cc:14
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0950 
	nop.m	 0
  (p9)	fma.s1	f47=f48, f47, f47			    //104 	cc:18
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0960 
	nop.m	 0
  (p9)	fma.s1	f48=f48, f48, f0			    //104 	cc:18
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0970 
	nop.m	 0
  (p9)	fma.d.s1 f47=f48, f47, f47			    //104 	cc:22
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0980 
	nop.m	 0
  (p9)	fma.s.s0 f46=f47, f1, f0, f46			    //104 	cc:26
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0990 
	nop.m	 0
	fmpy.s0	f49=f41, f46				    //104 	cc:30
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X09a0 
	nop.m	 0
	fcvt.fx.trunc.s0 f50=f49			    //104 	cc:34
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X09b0 
	getf.sig r35=f50				    //104 	cc:38
	nop.m	 0
	br.call.sptk.few b0=srand#;;			    //104 	cc:38
 }
 {   .mmi  //R-Addr: 0X09c0 
	mov	gp=r34;;				    //104 	cc:49
	mov	r11=1					    //105 	cc:0
	adds	r10=i$, sp;;				    //105 	cc:0
 }
 {   .mmb  //R-Addr: 0X09d0 
	st4	[r10]=r11				    //105 	cc:1
	nop.m	 0
	br.cond.sptk.few $LN20@main#;;			    //105 	cc:1
 }
$LN19@main:
 {   .mib  //R-Addr: 0X09e0 
	adds	r9=i$, sp				    //105 	cc:0
	adds	r30=i$, sp				    //105 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X09f0 
	ld4	r8=[r9];;				    //105 	cc:1
	adds	r31=1, r8				    //105 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0a00 
	st4	[r30]=r31				    //105 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LN20@main:
 {   .mmi  //R-Addr: 0X0a10 
	adds	r29=i$, sp;;				    //105 	cc:0
	ld4	r28=[r29]				    //105 	cc:1
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0a20 
	cmp4.le.unc p14,p15=7, r28			    //105 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN18@main#;;			    //105 	cc:2
 }
 {   .mmi  //R-Addr: 0X0a30 
	adds	r27=i$, sp				    //107 	cc:0
	adds	r25=$T4025, sp				    //107 	cc:0
	adds	r22=$T4025, sp				    //107 	cc:0
 }
 {   .mib  //R-Addr: 0X0a40 
	adds	r19=$T4025, sp				    //107 	cc:0
	adds	r18=$T4025, sp				    //107 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0a50 
	ld4	r26=[r27];;				    //107 	cc:1
	st4	[r25]=r26				    //107 	cc:2
	nop.i	 0
 }
 {   .mmi  //R-Addr: 0X0a60 
	ld4	r21=[r22];;				    //107 	cc:2
	adds	r20=-1, r21				    //107 	cc:3
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0a70 
	st4	[r19]=r20				    //107 	cc:4
	ld4	r17=[r18]				    //107 	cc:4
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0a80 
	cmp4.ltu.unc p14,p15=5, r17			    //107 	cc:5
	nop.m	 0
  (p14)	br.cond.dptk.few $LN16@main#;;			    //107 	cc:5
 }
 {   .mmi  //R-Addr: 0X0a90 
	adds	r16=$T4025, sp;;			    //107 	cc:6
	ld4	r15=[r16]				    //107 	cc:7
	nop.i	 0;;
 }
$LN29@main:
 {   .mii  //R-Addr: 0X0aa0 
	cmp4.eq	p6,p0=0, r15				    //107 	cc:9
	cmp4.eq	p7,p0=1, r15				    //107 	cc:9
	cmp4.eq	p8,p9=2, r15				    //107 	cc:9
 }
 {   .bbb  //R-Addr: 0X0ab0 
  (p6)	br.cond.sptk.few $LN15@main#			    //107 	cc:9
  (p7)	br.cond.sptk.few $LN14@main#			    //107 	cc:9
  (p8)	br.cond.sptk.few $LN13@main#;;			    //107 	cc:9
 }
 {   .mii  //R-Addr: 0X0ac0 
	cmp4.eq	p10,p0=3, r15				    //107 	cc:9
	cmp4.eq	p11,p0=4, r15				    //107 	cc:9
	cmp4.eq	p12,p13=5, r15				    //107 	cc:9
 }
 {   .bbb  //R-Addr: 0X0ad0 
  (p10)	br.cond.sptk.few $LN12@main#			    //107 	cc:9
  (p11)	br.cond.sptk.few $LN11@main#			    //107 	cc:9
  (p12)	br.cond.sptk.few $LN10@main#;;			    //107 	cc:9
 }
$LN15@main:
 {   .mmi  //R-Addr: 0X0ae0 
	mov	r38=25					    //110 	cc:0
	mov	r37=0					    //110 	cc:0
	mov	r36=70					    //110 	cc:0, 00000046H
 }
 {   .mmb  //R-Addr: 0X0af0 
	mov	r35=5					    //110 	cc:0
	nop.m	 0
	br.call.sptk.few b0=gamesx#;;			    //110 	cc:0
 }
 {   .mmi  //R-Addr: 0X0b00 
	addl	r11=@ltoff($SG3979#),gp;;		    //111 	cc:0
	ld8	r35=[r11]				    //111 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0b10 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //111 	cc:1
 }
 {   .mmb  //R-Addr: 0X0b20 
	mov	gp=r34					    //111 	cc:13
	nop.m	 0
	br.cond.sptk.few $LN16@main#;;			    //112 	cc:0
 }
$LN14@main:
 {   .mmi  //R-Addr: 0X0b30 
	mov	r38=26					    //114 	cc:0
	mov	r37=0					    //114 	cc:0
	mov	r36=69					    //114 	cc:0, 00000045H
 }
 {   .mmb  //R-Addr: 0X0b40 
	mov	r35=5					    //114 	cc:0
	nop.m	 0
	br.call.sptk.few b0=gamesx#;;			    //114 	cc:0
 }
 {   .mmi  //R-Addr: 0X0b50 
	addl	r10=@ltoff($SG3981#),gp;;		    //115 	cc:0
	ld8	r35=[r10]				    //115 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0b60 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //115 	cc:1
 }
 {   .mmb  //R-Addr: 0X0b70 
	mov	gp=r34					    //115 	cc:13
	nop.m	 0
	br.cond.sptk.few $LN16@main#;;			    //116 	cc:0
 }
$LN13@main:
 {   .mmi  //R-Addr: 0X0b80 
	mov	r38=0					    //118 	cc:0
	mov	r37=1					    //118 	cc:0
	mov	r36=59					    //118 	cc:0, 0000003bH
 }
 {   .mmb  //R-Addr: 0X0b90 
	mov	r35=7					    //118 	cc:0
	nop.m	 0
	br.call.sptk.few b0=gamesx#;;			    //118 	cc:0
 }
 {   .mmi  //R-Addr: 0X0ba0 
	addl	r9=@ltoff($SG3983#),gp;;		    //119 	cc:0
	ld8	r35=[r9]				    //119 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0bb0 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //119 	cc:1
 }
 {   .mmi  //R-Addr: 0X0bc0 
	mov	gp=r34;;				    //119 	cc:12
	mov	r38=0					    //120 	cc:0
	mov	r37=1					    //120 	cc:0
 }
 {   .mib  //R-Addr: 0X0bd0 
	mov	r36=59					    //120 	cc:0, 0000003bH
	mov	r35=7					    //120 	cc:0
	br.call.sptk.few b0=gamesx#;;			    //120 	cc:0
 }
 {   .mmi  //R-Addr: 0X0be0 
	addl	r8=@ltoff($SG3984#),gp;;		    //121 	cc:0
	ld8	r35=[r8]				    //121 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0bf0 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //121 	cc:1
 }
 {   .mmb  //R-Addr: 0X0c00 
	mov	gp=r34					    //121 	cc:13
	nop.m	 0
	br.cond.sptk.few $LN16@main#;;			    //122 	cc:0
 }
$LN12@main:
 {   .mmi  //R-Addr: 0X0c10 
	mov	r38=4					    //124 	cc:0
	mov	r37=0					    //124 	cc:0
	mov	r36=60					    //124 	cc:0, 0000003cH
 }
 {   .mmb  //R-Addr: 0X0c20 
	mov	r35=5					    //124 	cc:0
	nop.m	 0
	br.call.sptk.few b0=gamesx#;;			    //124 	cc:0
 }
 {   .mmi  //R-Addr: 0X0c30 
	addl	r31=@ltoff($SG3986#),gp;;		    //125 	cc:0
	ld8	r35=[r31]				    //125 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0c40 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //125 	cc:1
 }
 {   .mmb  //R-Addr: 0X0c50 
	mov	gp=r34					    //125 	cc:13
	nop.m	 0
	br.cond.sptk.few $LN16@main#;;			    //126 	cc:0
 }
$LN11@main:
 {   .mmi  //R-Addr: 0X0c60 
	mov	r38=0					    //128 	cc:0
	mov	r37=1					    //128 	cc:0
	mov	r36=39					    //128 	cc:0, 00000027H
 }
 {   .mmb  //R-Addr: 0X0c70 
	mov	r35=5					    //128 	cc:0
	nop.m	 0
	br.call.sptk.few b0=gamesx#;;			    //128 	cc:0
 }
 {   .mmi  //R-Addr: 0X0c80 
	addl	r30=@ltoff($SG3988#),gp;;		    //129 	cc:0
	ld8	r35=[r30]				    //129 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0c90 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //129 	cc:1
 }
 {   .mmb  //R-Addr: 0X0ca0 
	mov	gp=r34					    //129 	cc:13
	nop.m	 0
	br.cond.sptk.few $LN16@main#;;			    //130 	cc:0
 }
$LN10@main:
 {   .mmi  //R-Addr: 0X0cb0 
	mov	r38=0					    //132 	cc:0
	mov	r37=1					    //132 	cc:0
	mov	r36=80					    //132 	cc:0, 00000050H
 }
 {   .mmb  //R-Addr: 0X0cc0 
	mov	r35=10					    //132 	cc:0
	nop.m	 0
	br.call.sptk.few b0=gamesx#;;			    //132 	cc:0
 }
 {   .mmi  //R-Addr: 0X0cd0 
	addl	r29=@ltoff($SG3990#),gp;;		    //133 	cc:0
	ld8	r35=[r29]				    //133 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0ce0 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //133 	cc:1
 }
 {   .mmi  //R-Addr: 0X0cf0 
	mov	gp=r34;;				    //133 	cc:12
	nop.m	 0
	nop.i	 0;;
 }
$LN16@main:
 {   .mmb  //R-Addr: 0X0d00 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN19@main#;;			    //137 	cc:0
 }
$LN18@main:
 {   .mib  //R-Addr: 0X0d10 
	mov	r28=1					    //138 	cc:0
	adds	r27=ia$, sp				    //138 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0d20 
	st4	[r27]=r28				    //138 	cc:1
	nop.m	 0
	br.cond.sptk.few $LN9@main#;;			    //138 	cc:1
 }
$LN8@main:
 {   .mib  //R-Addr: 0X0d30 
	adds	r26=ia$, sp				    //138 	cc:0
	adds	r21=ia$, sp				    //138 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0d40 
	ld4	r25=[r26];;				    //138 	cc:1
	adds	r22=1, r25				    //138 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0d50 
	st4	[r21]=r22				    //138 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LN9@main:
 {   .mmi  //R-Addr: 0X0d60 
	adds	r20=ia$, sp;;				    //138 	cc:0
	ld4	r19=[r20]				    //138 	cc:1
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0d70 
	cmp4.le.unc p14,p15=5, r19			    //138 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN7@main#;;			    //138 	cc:2
 }
 {   .mmi  //R-Addr: 0X0d80 
	adds	r18=ia$, sp				    //140 	cc:0
	adds	r16=$T4026, sp				    //140 	cc:0
	adds	r15=$T4026, sp				    //140 	cc:0
 }
 {   .mib  //R-Addr: 0X0d90 
	adds	r9=$T4026, sp				    //140 	cc:0
	adds	r8=$T4026, sp				    //140 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0da0 
	ld4	r17=[r18];;				    //140 	cc:1
	st4	[r16]=r17				    //140 	cc:2
	nop.i	 0
 }
 {   .mmi  //R-Addr: 0X0db0 
	ld4	r11=[r15];;				    //140 	cc:2
	adds	r10=-1, r11				    //140 	cc:3
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0dc0 
	st4	[r9]=r10				    //140 	cc:4
	ld4	r31=[r8]				    //140 	cc:4
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0dd0 
	cmp4.ltu.unc p14,p15=3, r31			    //140 	cc:5
	nop.m	 0
  (p14)	br.cond.dptk.few $LN5@main#;;			    //140 	cc:5
 }
 {   .mmi  //R-Addr: 0X0de0 
	adds	r30=$T4026, sp;;			    //140 	cc:6
	ld4	r29=[r30]				    //140 	cc:7
	nop.i	 0;;
 }
$LN30@main:
 {   .mii  //R-Addr: 0X0df0 
	cmp4.eq	p6,p0=0, r29				    //140 	cc:9
	cmp4.eq	p7,p0=1, r29				    //140 	cc:9
	cmp4.eq	p8,p9=2, r29				    //140 	cc:9
 }
 {   .bbb  //R-Addr: 0X0e00 
  (p6)	br.cond.sptk.few $LN4@main#			    //140 	cc:9
  (p7)	br.cond.sptk.few $LN3@main#			    //140 	cc:9
  (p8)	br.cond.sptk.few $LN2@main#;;			    //140 	cc:9
 }
 {   .mmb  //R-Addr: 0X0e10 
	cmp4.eq	p10,p11=3, r29				    //140 	cc:0
	nop.m	 0
  (p10)	br.cond.sptk.few $LN1@main#;;			    //140 	cc:0
 }
$LN4@main:
 {   .mmb  //R-Addr: 0X0e20 
	mov	r35=3					    //143 	cc:0
	nop.m	 0
	br.call.sptk.few b0=numbersx#;;			    //143 	cc:0
 }
 {   .mmi  //R-Addr: 0X0e30 
	addl	r28=@ltoff($SG3999#),gp;;		    //144 	cc:0
	ld8	r35=[r28]				    //144 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0e40 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //144 	cc:1
 }
 {   .mmb  //R-Addr: 0X0e50 
	mov	gp=r34					    //144 	cc:13
	nop.m	 0
	br.cond.sptk.few $LN5@main#;;			    //145 	cc:0
 }
$LN3@main:
 {   .mmb  //R-Addr: 0X0e60 
	mov	r35=3					    //147 	cc:0
	nop.m	 0
	br.call.sptk.few b0=numbersx#;;			    //147 	cc:0
 }
 {   .mmi  //R-Addr: 0X0e70 
	addl	r27=@ltoff($SG4001#),gp;;		    //148 	cc:0
	ld8	r35=[r27]				    //148 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0e80 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //148 	cc:1
 }
 {   .mmb  //R-Addr: 0X0e90 
	mov	gp=r34					    //148 	cc:13
	nop.m	 0
	br.cond.sptk.few $LN5@main#;;			    //149 	cc:0
 }
$LN2@main:
 {   .mmb  //R-Addr: 0X0ea0 
	mov	r35=4					    //151 	cc:0
	nop.m	 0
	br.call.sptk.few b0=numbersx#;;			    //151 	cc:0
 }
 {   .mmi  //R-Addr: 0X0eb0 
	addl	r26=@ltoff($SG4003#),gp;;		    //152 	cc:0
	ld8	r35=[r26]				    //152 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0ec0 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //152 	cc:1
 }
 {   .mmb  //R-Addr: 0X0ed0 
	mov	gp=r34					    //152 	cc:13
	nop.m	 0
	br.cond.sptk.few $LN5@main#;;			    //153 	cc:0
 }
$LN1@main:
 {   .mmb  //R-Addr: 0X0ee0 
	mov	r35=4					    //155 	cc:0
	nop.m	 0
	br.call.sptk.few b0=numbersx#;;			    //155 	cc:0
 }
 {   .mmi  //R-Addr: 0X0ef0 
	addl	r25=@ltoff($SG4005#),gp;;		    //156 	cc:0
	ld8	r35=[r25]				    //156 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0f00 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //156 	cc:1
 }
 {   .mmi  //R-Addr: 0X0f10 
	mov	gp=r34;;				    //156 	cc:12
	nop.m	 0
	nop.i	 0;;
 }
$LN5@main:
 {   .mmb  //R-Addr: 0X0f20 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN8@main#;;			    //160 	cc:0
 }
$LN7@main:
 {   .mmi  //R-Addr: 0X0f30 
	mov	r38=0					    //161 	cc:0
	mov	r37=1					    //161 	cc:0
	mov	r36=80					    //161 	cc:0, 00000050H
 }
 {   .mmb  //R-Addr: 0X0f40 
	mov	r35=10					    //161 	cc:0
	nop.m	 0
	br.call.sptk.few b0=gamesx#;;			    //161 	cc:0
 }
 {   .mmi  //R-Addr: 0X0f50 
	addl	r22=@ltoff($SG4006#),gp;;		    //162 	cc:0
	ld8	r35=[r22]				    //162 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0f60 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //162 	cc:1
 }
 {   .mmi  //R-Addr: 0X0f70 
	mov	gp=r34;;				    //162 	cc:12
	addl	r21=@ltoff($SG4007#),gp			    //163 	cc:0
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0f80 
	ld8	r35=[r21]				    //163 	cc:1
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //163 	cc:1
 }
 {   .mmb  //R-Addr: 0X0f90 
	mov	gp=r34					    //163 	cc:13
	nop.m	 0
	br.call.sptk.few b0=getchar#;;			    //164 	cc:0
 }
 {   .mmi  //R-Addr: 0X0fa0 
	mov	gp=r34;;				    //164 	cc:11
	mov	r8=r0					    //165 	cc:0
	nop.i	 0;;
 }
$LN27@main:
 {   .mii  //R-Addr: 0X0fb0 
	adds	sp=160, sp				    //166 	cc:0, 000000a0H
	mov.ret	b0=r32;;				    //166 	cc:0
	mov.i	ar.pfs=r33				    //166 	cc:1
 }
 {   .mmb  //R-Addr: 0X0fc0 
	nop.m	 0
	nop.m	 0
	br.ret.sptk.many b0;;				    //166 	cc:1
 }
// End code for function:
	.endp	main#
	.type	_localtime64#	,@function 
        .global _localtime64#
	.section	.pdata
$T4036:	data4	@imagerel(localtime#)
	data4	@imagerel(localtime#+128)
	data4	@imagerel($T4035#)
	.section	.xdata
	.skip 8
$T4035:	data2	03H
	data2	00H
	data4	02H
	string	"\x07"		//R1:prologue size 7
	string	"\xe6\x00"	//P7:pfs_when time 0
	string	"\xb1\x22"	//P3:pfs_gr 34
	string	"\xe0\x01\x02"	//P7:mem_stack_f time 1 size 2
	string	"\xe4\x02"	//P7:rp_when time 2
	string	"\xb0\xa1"	//P3:rp_gr 33
	string	"\x31"		//R1:body size size 17
	string	"\x81"		//B1:label_state 1
	string	"\xc0\x05"	//B2:ecount 0 time 5
// Function compile flags: /Odtp
	.section	.text

// Begin code for function: localtime:
	.proc	localtime#
	.align 32
$T4034	= 16
_Time$	= 32
localtime: 
// _Time$ = r32
// Output regs: r36-r36
// File c:\program files (x86)\microsoft visual studio 10.0\vc\bin\x86_ia64\time.inl
 {   .mmi  //R-Addr: 0X00 
	alloc	r34=1, 3, 1, 0				    //113 	cc:0
	adds	sp=-32, sp				    //113 	cc:0
	mov	r33=b0					    //113 	cc:0
 }
 {   .mmi  //R-Addr: 0X010 
	mov	r35=gp;;				    //113 	cc:0
	ld8.nta	r2=[sp]					    //113 	cc:1
	adds	r31=_Time$, sp;;
 }
 {   .mmi  //R-Addr: 0X020 
	st8	[r31]=r32;;
	adds	r30=_Time$, sp				    //116 	cc:0
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X030 
	ld8	r36=[r30]				    //116 	cc:1
	nop.m	 0
	br.call.sptk.few b0=_localtime64#;;		    //116 	cc:1
 }
 {   .mmi  //R-Addr: 0X040 
	adds	r29=$T4034, sp				    //116 	cc:12
	adds	r28=$T4034, sp				    //116 	cc:12
	mov	gp=r35;;				    //116 	cc:12
 }
 {   .mmb  //R-Addr: 0X050 
	st8	[r29]=r8				    //116 	cc:13
	ld8	r8=[r28]				    //116 	cc:13
	nop.b	 0;;
 }
 {   .mii  //R-Addr: 0X060 
	adds	sp=32, sp				    //118 	cc:0
	mov.ret	b0=r33;;				    //118 	cc:0
	mov.i	ar.pfs=r34				    //118 	cc:1
 }
 {   .mmb  //R-Addr: 0X070 
	nop.m	 0
	nop.m	 0
	br.ret.sptk.many b0;;				    //118 	cc:1
 }
// End code for function:
	.endp	localtime#
	.type	_time64#	,@function 
        .global _time64#
	.section	.pdata
$T4040:	data4	@imagerel(time#)
	data4	@imagerel(time#+128)
	data4	@imagerel($T4039#)
	.section	.xdata
	.skip 16
$T4039:	data2	03H
	data2	00H
	data4	02H
	string	"\x07"		//R1:prologue size 7
	string	"\xe6\x00"	//P7:pfs_when time 0
	string	"\xb1\x22"	//P3:pfs_gr 34
	string	"\xe0\x01\x02"	//P7:mem_stack_f time 1 size 2
	string	"\xe4\x02"	//P7:rp_when time 2
	string	"\xb0\xa1"	//P3:rp_gr 33
	string	"\x31"		//R1:body size size 17
	string	"\x81"		//B1:label_state 1
	string	"\xc0\x05"	//B2:ecount 0 time 5
// Function compile flags: /Odtp
	.section	.text

// Begin code for function: time:
	.proc	time#
	.align 32
$T4038	= 16
_Time$	= 32
time: 
// _Time$ = r32
// Output regs: r36-r36
 {   .mmi  //R-Addr: 0X00 
	alloc	r34=1, 3, 1, 0				    //132 	cc:0
	adds	sp=-32, sp				    //132 	cc:0
	mov	r33=b0					    //132 	cc:0
 }
 {   .mmi  //R-Addr: 0X010 
	mov	r35=gp;;				    //132 	cc:0
	ld8.nta	r2=[sp]					    //132 	cc:1
	adds	r31=_Time$, sp;;
 }
 {   .mmi  //R-Addr: 0X020 
	st8	[r31]=r32;;
	adds	r30=_Time$, sp				    //133 	cc:0
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X030 
	ld8	r36=[r30]				    //133 	cc:1
	nop.m	 0
	br.call.sptk.few b0=_time64#;;			    //133 	cc:1
 }
 {   .mmi  //R-Addr: 0X040 
	adds	r29=$T4038, sp				    //133 	cc:12
	adds	r28=$T4038, sp				    //133 	cc:12
	mov	gp=r35;;				    //133 	cc:12
 }
 {   .mmb  //R-Addr: 0X050 
	st8	[r29]=r8				    //133 	cc:13
	ld8	r8=[r28]				    //133 	cc:13
	nop.b	 0;;
 }
 {   .mii  //R-Addr: 0X060 
	adds	sp=32, sp				    //134 	cc:0
	mov.ret	b0=r33;;				    //134 	cc:0
	mov.i	ar.pfs=r34				    //134 	cc:1
 }
 {   .mmb  //R-Addr: 0X070 
	nop.m	 0
	nop.m	 0
	br.ret.sptk.many b0;;				    //134 	cc:1
 }
// End code for function:
	.endp	time#
        .global __$ArrayPad$#
	.type	rand#	,@function 
        .global rand#
	.type	__security_cookie#	,@object 
        .global __security_cookie#
	.type	__GSHandlerCheck#	,@function 
        .global __GSHandlerCheck#
	.type	__security_check_cookie#	,@function 
        .global __security_check_cookie#
	.section	.pdata
$T4052:	data4	@imagerel(gamesx#)
	data4	@imagerel(gamesx#+2432)
	data4	@imagerel($T4051#)
	.section	.xdata
	.skip 16
$T4051:	data2	03H
	data2	03H
	data4	03H
	string	"\x14"		//R1:prologue size 20
	string	"\xe6\x00"	//P7:pfs_when time 0
	string	"\xb1\x25"	//P3:pfs_gr 37
	string	"\xe0\x01\x0b"	//P7:mem_stack_f time 1 size 11
	string	"\xe4\x02"	//P7:rp_when time 2
	string	"\xb0\xa4"	//P3:rp_gr 36
	string	"\xea\x08"	//P7:lc_when time 8
	string	"\xb2\xa6"	//P3:lc_gr 38
	string	"\x61\xb4\x03"	//R3:body size 436
	string	"\x81"		//B1:label_state 1
	string	"\xc0\x06"	//B2:ecount 0 time 6
	string	"\x00\x00"	//padding
	data4	@imagerel(__GSHandlerCheck#)
	data4	0ffffffd0H
// Function compile flags: /Odtp
	.section	.text

// Begin code for function: gamesx:
	.proc	gamesx#
	.align 32
y$	= 16
x$	= 20
a$	= 24
jc$	= 28
hc$	= 32
zy$	= 36
z$	= 40
e$	= 44
GGGc$	= 48
__$ArrayPad$	= 128
$T4046	= 136
$T4047	= 144
$T4048	= 152
$T4049	= 156
xSIZEc$	= 160
xRANGEc$	= 168
islotto$	= 176
ball$	= 184
gamesx:	
// xSIZEc$ = r32
// xRANGEc$ = r33
// islotto$ = r34
// ball$ = r35
// Output regs: r40-r41
// File c:\program files (x86)\microsoft visual studio 10.0\vc\bin\x86_ia64\blottorch.c
 {   .mmi  //R-Addr: 0X00 
	alloc	r37=4, 4, 2, 0				    //12 	cc:0
	adds	sp=-176, sp				    //12 	cc:0, ffffff50H
	mov	r36=b0					    //12 	cc:0
 }
 {   .mib  //R-Addr: 0X010 
	addl	r27=@gprel(__security_cookie#),gp	    //12 	cc:0
	mov	r39=gp					    //12 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X020 
	ld8.nta	r2=[sp]					    //12 	cc:1
	adds	r31=xSIZEc$, sp
	mov.i	r38=ar.lc				    //12 	cc:1
 }
 {   .mmi  //R-Addr: 0X030 
	adds	r30=xRANGEc$, sp
	adds	r29=islotto$, sp
	adds	r28=ball$, sp;;
 }
 {   .mmi  //R-Addr: 0X040 
	st4	[r31]=r32
	st4	[r30]=r33
	adds	r25=__$ArrayPad$, sp;;			    //12 	cc:2
 }
 {   .mmb  //R-Addr: 0X050 
	st1	[r29]=r34
	st4	[r28]=r35
	nop.b	 0
 }
 {   .mmi  //R-Addr: 0X060 
	ld8	r26=[r27];;				    //12 	cc:3
	st8	[r25]=r26				    //12 	cc:4
	nop.i	 0;;
 }
 {   .mmi  //R-Addr: 0X070 
	adds	r22=GGGc$, sp				    //13 	cc:0
	adds	r21=GGGc$+4, sp				    //13 	cc:0
	mov.i	ar.lc=8					    //13 	cc:0
 }
 {   .mmi  //R-Addr: 0X080 
	adds	r20=$T4046, sp				    //13 	cc:0
	adds	r19=$T4046, sp				    //13 	cc:0
	adds	r16=$T4047, sp;;			    //13 	cc:0
 }
 {   .mmb  //R-Addr: 0X090 
	st4	[r22]=r0				    //13 	cc:1
	st8	[r20]=r21				    //13 	cc:1
	nop.b	 0
 }
 {   .mmi  //R-Addr: 0X0a0 
	ld8	r18=[r19];;				    //13 	cc:1
	adds	r17=4, r18				    //13 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0b0 
	st8	[r16]=r17				    //13 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LL26@gamesx:						    // Start of loop
 {   .mmi  //R-Addr: 0X0c0 
	adds	r15=$T4046, sp				    //13 	cc:0
	adds	r10=$T4046, sp				    //13 	cc:0
	adds	r31=$T4046, sp				    //13 	cc:0
 }
 {   .mmi  //R-Addr: 0X0d0 
	adds	r30=$T4047, sp				    //13 	cc:0
	adds	r28=$T4047, sp				    //13 	cc:0
	adds	r25=$T4047, sp;;			    //13 	cc:0
 }
 {   .mmi  //R-Addr: 0X0e0 
	ld8	r11=[r15];;				    //13 	cc:1
	st4	[r11]=r0				    //13 	cc:2
	nop.i	 0
 }
 {   .mmi  //R-Addr: 0X0f0 
	ld8	r9=[r10];;				    //13 	cc:2
	adds	r8=8, r9				    //13 	cc:3
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0100 
	st8	[r31]=r8				    //13 	cc:4
	ld8	r29=[r30]				    //13 	cc:4
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0110 
	st4	[r29]=r0				    //13 	cc:5
	ld8	r27=[r28]				    //13 	cc:5
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0120 
	adds	r26=8, r27;;				    //13 	cc:6
	st8	[r25]=r26				    //13 	cc:7
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0130 
	nop.m	 0
	nop.m	 0
	br.cloop.sptk.many $LL26@gamesx#;;		    //13 	cc:7
 }
 {   .mmi  //R-Addr: 0X0140 
	adds	r22=$T4046, sp;;			    //13 	cc:0
	ld8	r21=[r22]				    //13 	cc:1
	nop.i	 0;;
 }
 {   .mmi  //R-Addr: 0X0150 
	st4	[r21]=r0;;				    //13 	cc:2
	adds	r20=hc$, sp				    //14 	cc:0
	nop.i	 0;;
 }
 {   .mmi  //R-Addr: 0X0160 
	st4	[r20]=r0;;				    //14 	cc:1
	adds	r19=jc$, sp				    //15 	cc:0
	nop.i	 0;;
 }
 {   .mmi  //R-Addr: 0X0170 
	st4	[r19]=r0;;				    //15 	cc:1
	adds	r18=a$, sp				    //17 	cc:0
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0180 
	st4	[r18]=r0				    //17 	cc:1
	nop.m	 0
	br.cond.sptk.few $LN23@gamesx#;;		    //17 	cc:1
 }
$LN22@gamesx:
 {   .mib  //R-Addr: 0X0190 
	adds	r17=a$, sp				    //17 	cc:0
	adds	r11=a$, sp				    //17 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X01a0 
	ld4	r16=[r17];;				    //17 	cc:1
	adds	r15=1, r16				    //17 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X01b0 
	st4	[r11]=r15				    //17 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LN23@gamesx:
 {   .mib  //R-Addr: 0X01c0 
	adds	r10=a$, sp				    //17 	cc:0
	adds	r8=xSIZEc$, sp				    //17 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X01d0 
	ld4	r9=[r10]				    //17 	cc:1
	ld4	r31=[r8]				    //17 	cc:1
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X01e0 
	cmp4.ge.unc p14,p15=r9, r31			    //17 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN21@gamesx#;;		    //17 	cc:2
 }
 {   .mmi  //R-Addr: 0X01f0 
	adds	r30=e$, sp;;				    //19 	cc:0
	st4	[r30]=r0				    //19 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0200 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN20@gamesx#;;		    //19 	cc:1
 }
$LN19@gamesx:
 {   .mib  //R-Addr: 0X0210 
	adds	r29=e$, sp				    //19 	cc:0
	adds	r26=e$, sp				    //19 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0220 
	ld4	r28=[r29];;				    //19 	cc:1
	adds	r27=1, r28				    //19 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0230 
	st4	[r26]=r27				    //19 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LN20@gamesx:
 {   .mib  //R-Addr: 0X0240 
	adds	r25=e$, sp				    //19 	cc:0
	adds	r21=xSIZEc$, sp				    //19 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0250 
	ld4	r22=[r25]				    //19 	cc:1
	ld4	r20=[r21]				    //19 	cc:1
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0260 
	cmp4.ge.unc p14,p15=r22, r20			    //19 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN18@gamesx#;;		    //19 	cc:2
 }
 {   .mmi  //R-Addr: 0X0270 
	adds	r19=x$, sp;;				    //21 	cc:0
	st4	[r19]=r0				    //21 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0280 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN17@gamesx#;;		    //21 	cc:1
 }
$LN16@gamesx:
 {   .mib  //R-Addr: 0X0290 
	adds	r18=x$, sp				    //21 	cc:0
	adds	r15=x$, sp				    //21 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X02a0 
	ld4	r17=[r18];;				    //21 	cc:1
	adds	r16=1, r17				    //21 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X02b0 
	st4	[r15]=r16				    //21 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LN17@gamesx:
 {   .mib  //R-Addr: 0X02c0 
	adds	r11=x$, sp				    //21 	cc:0
	adds	r9=xSIZEc$, sp				    //21 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X02d0 
	ld4	r10=[r11]				    //21 	cc:1
	ld4	r8=[r9]					    //21 	cc:1
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X02e0 
	cmp4.ge.unc p14,p15=r10, r8			    //21 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN15@gamesx#;;		    //21 	cc:2
 }
 {   .mmi  //R-Addr: 0X02f0 
	adds	r31=y$, sp;;				    //23 	cc:0
	st4	[r31]=r0				    //23 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0300 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN14@gamesx#;;		    //23 	cc:1
 }
$LN13@gamesx:
 {   .mib  //R-Addr: 0X0310 
	adds	r30=y$, sp				    //23 	cc:0
	adds	r27=y$, sp				    //23 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0320 
	ld4	r29=[r30];;				    //23 	cc:1
	adds	r28=1, r29				    //23 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0330 
	st4	[r27]=r28				    //23 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LN14@gamesx:
 {   .mib  //R-Addr: 0X0340 
	adds	r26=y$, sp				    //23 	cc:0
	adds	r22=xSIZEc$, sp				    //23 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0350 
	ld4	r25=[r26]				    //23 	cc:1
	ld4	r21=[r22]				    //23 	cc:1
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0360 
	cmp4.ge.unc p14,p15=r25, r21			    //23 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN12@gamesx#;;		    //23 	cc:2
 }
 {   .mmi  //R-Addr: 0X0370 
	adds	r20=z$, sp;;				    //25 	cc:0
	st4	[r20]=r0				    //25 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0380 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN11@gamesx#;;		    //25 	cc:1
 }
$LN10@gamesx:
 {   .mib  //R-Addr: 0X0390 
	adds	r19=z$, sp				    //25 	cc:0
	adds	r16=z$, sp				    //25 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X03a0 
	ld4	r18=[r19];;				    //25 	cc:1
	adds	r17=1, r18				    //25 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X03b0 
	st4	[r16]=r17				    //25 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LN11@gamesx:
 {   .mib  //R-Addr: 0X03c0 
	adds	r15=z$, sp				    //25 	cc:0
	adds	r10=xSIZEc$, sp				    //25 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X03d0 
	ld4	r11=[r15]				    //25 	cc:1
	ld4	r9=[r10]				    //25 	cc:1
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X03e0 
	cmp4.ge.unc p14,p15=r11, r9			    //25 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN9@gamesx#;;			    //25 	cc:2
 }
 {   .mmi  //R-Addr: 0X03f0 
	adds	r8=z$, sp				    //27 	cc:0
	adds	r28=GGGc$, sp				    //27 	cc:0
	adds	r26=hc$, sp;;				    //27 	cc:0
 }
 {   .mmb  //R-Addr: 0X0400 
	ld4	r31=[r8]				    //27 	cc:1
	ld4	r25=[r26]				    //27 	cc:1
	nop.b	 0;;
 }
 {   .mii  //R-Addr: 0X0410 
	nop.m	 0
	sxt4	r30=r31;;				    //27 	cc:2
	shl	r29=r30, 2;;				    //27 	cc:3
 }
 {   .mmi  //R-Addr: 0X0420 
	add	r27=r28, r29;;				    //27 	cc:4
	ld4	r22=[r27]				    //27 	cc:5
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0430 
	cmp4.ne.unc p14,p15=r25, r22			    //27 	cc:6
	nop.m	 0
  (p14)	br.cond.dptk.few $LN8@gamesx#;;			    //27 	cc:6
 }
$LN7@gamesx:
 {   .mmi  //R-Addr: 0X0440 
	mov	r21=1;;					    //29 	cc:0
	cmp4.eq.unc p14,p15=r0, r21			    //29 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0450 
	nop.m	 0
	nop.m	 0
  (p14)	br.cond.dptk.few $LN8@gamesx#;;			    //29 	cc:1
 }
 {   .mmb  //R-Addr: 0X0460 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=rand#;;			    //31 	cc:0
 }
 {   .mmi  //R-Addr: 0X0470 
	adds	r20=$T4048, sp				    //31 	cc:11
	adds	r19=$T4048, sp				    //31 	cc:11
	adds	r17=xRANGEc$, sp			    //31 	cc:11
 }
 {   .mmi  //R-Addr: 0X0480 
	mov	r10=65501				    //31 	cc:11, 0000ffddH
	adds	r31=jc$, sp				    //31 	cc:11
	mov	gp=r39;;				    //31 	cc:11
 }
 {   .mmb  //R-Addr: 0X0490 
	st4	[r20]=r8				    //31 	cc:12
	ld4	r18=[r19]				    //31 	cc:12
	nop.b	 0
 }
 {   .mmb  //R-Addr: 0X04a0 
	ld4	r16=[r17]				    //31 	cc:12
	setf.exp f9=r10					    //31 	cc:12
	nop.b	 0;;
 }
 {   .mii  //R-Addr: 0X04b0 
	nop.m	 0
	sxt4	r11=r16					    //31 	cc:13
	sxt4	r15=r18;;				    //31 	cc:13
 }
 {   .mmi  //R-Addr: 0X04c0 
	setf.sig f6=r15					    //31 	cc:14
	setf.sig f7=r11					    //31 	cc:14
	sub	r10=r0, r11, r10			    //31 	cc:14
 }
 {   .mmi  //R-Addr: 0X04d0 
	cmp.eq.unc p15,p0=0, r11;;			    //31 	cc:14
  (p15)	break.m	 1					    //31 	cc:15
	nop.i	 0;;
 }
 {   .mfb  //R-Addr: 0X04e0 
	nop.m	 0
	fcvt.xf	f8=f6					    //31 	cc:20
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X04f0 
	nop.m	 0
	fcvt.xf	f7=f7					    //31 	cc:20
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0500 
	nop.m	 0
	frcpa.s1 f10,p6=f8, f7				    //31 	cc:24
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0510 
	nop.m	 0
  (p6)	fma.s1	f11=f8, f10, f0				    //31 	cc:28
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0520 
	nop.m	 0
  (p6)	fnma.s1	f10=f7, f10, f1				    //31 	cc:28
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0530 
	setf.sig f7=r10, f7				    //31 	cc:29
	nop.m	 0
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0540 
	nop.m	 0
  (p6)	fma.s1	f8=f10, f10, f9, f8			    //31 	cc:32
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0550 
	nop.m	 0
  (p6)	fma.s1	f11=f10, f11, f11			    //31 	cc:32
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0560 
	nop.m	 0
  (p6)	fma.s1	f10=f8, f11, f11, f10			    //31 	cc:36
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0570 
	nop.m	 0
	fcvt.fx.trunc.s1 f8=f10, f8			    //31 	cc:40
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0580 
	nop.m	 0
	xma.l	f10=f8, f7, f6, f10			    //31 	cc:44
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0590 
	getf.sig r9=f10;;				    //31 	cc:48
	adds	r8=1, r9				    //31 	cc:53
	nop.i	 0;;
 }
 {   .mmi  //R-Addr: 0X05a0 
	st4	[r31]=r8;;				    //31 	cc:54
	adds	r30=z$, sp				    //32 	cc:0
	adds	r26=GGGc$, sp				    //32 	cc:0
 }
 {   .mmi  //R-Addr: 0X05b0 
	adds	r22=jc$, sp;;				    //32 	cc:0
	ld4	r29=[r30]				    //32 	cc:1
	nop.i	 0
 }
 {   .mmi  //R-Addr: 0X05c0 
	ld4	r21=[r22];;				    //32 	cc:1
	nop.m	 0
	sxt4	r28=r29;;				    //32 	cc:2
 }
 {   .mii  //R-Addr: 0X05d0 
	nop.m	 0
	shl	r27=r28, 2;;				    //32 	cc:3
	add	r25=r26, r27;;				    //32 	cc:4
 }
 {   .mmi  //R-Addr: 0X05e0 
	ld4	r20=[r25];;				    //32 	cc:5
	cmp4.eq.unc p14,p15=r21, r20			    //32 	cc:6
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X05f0 
	nop.m	 0
	nop.m	 0
  (p14)	br.cond.dptk.few $LN5@gamesx#;;			    //32 	cc:6
 }
 {   .mib  //R-Addr: 0X0600 
	adds	r19=jc$, sp				    //34 	cc:0
	adds	r17=hc$, sp				    //34 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0610 
	ld4	r18=[r19];;				    //34 	cc:1
	st4	[r17]=r18				    //34 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0620 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN8@gamesx#;;			    //35 	cc:0
 }
$LN5@gamesx:
 {   .mmb  //R-Addr: 0X0630 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN7@gamesx#;;			    //37 	cc:0
 }
$LN8@gamesx:
 {   .mmb  //R-Addr: 0X0640 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN10@gamesx#;;		    //40 	cc:0
 }
$LN9@gamesx:
 {   .mmb  //R-Addr: 0X0650 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN13@gamesx#;;		    //42 	cc:0
 }
$LN12@gamesx:
 {   .mmb  //R-Addr: 0X0660 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN16@gamesx#;;		    //43 	cc:0
 }
$LN15@gamesx:
 {   .mmb  //R-Addr: 0X0670 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN19@gamesx#;;		    //44 	cc:0
 }
$LN18@gamesx:
 {   .mmi  //R-Addr: 0X0680 
	adds	r16=a$, sp				    //45 	cc:0
	adds	r9=GGGc$, sp				    //45 	cc:0
	adds	r31=hc$, sp;;				    //45 	cc:0
 }
 {   .mmb  //R-Addr: 0X0690 
	ld4	r15=[r16]				    //45 	cc:1
	ld4	r30=[r31]				    //45 	cc:1
	nop.b	 0;;
 }
 {   .mii  //R-Addr: 0X06a0 
	nop.m	 0
	sxt4	r11=r15;;				    //45 	cc:2
	shl	r10=r11, 2;;				    //45 	cc:3
 }
 {   .mmi  //R-Addr: 0X06b0 
	add	r8=r9, r10;;				    //45 	cc:4
	st4	[r8]=r30				    //45 	cc:5
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X06c0 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN22@gamesx#;;		    //46 	cc:0
 }
$LN21@gamesx:
 {   .mmi  //R-Addr: 0X06d0 
	adds	r29=zy$, sp;;				    //47 	cc:0
	st4	[r29]=r0				    //47 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X06e0 
	nop.m	 0
	nop.m	 0
	br.cond.sptk.few $LN4@gamesx#;;			    //47 	cc:1
 }
$LN3@gamesx:
 {   .mib  //R-Addr: 0X06f0 
	adds	r28=zy$, sp				    //47 	cc:0
	adds	r25=zy$, sp				    //47 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0700 
	ld4	r27=[r28];;				    //47 	cc:1
	adds	r26=1, r27				    //47 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0710 
	st4	[r25]=r26				    //47 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LN4@gamesx:
 {   .mib  //R-Addr: 0X0720 
	adds	r22=zy$, sp				    //47 	cc:0
	adds	r20=xSIZEc$, sp				    //47 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0730 
	ld4	r21=[r22]				    //47 	cc:1
	ld4	r19=[r20]				    //47 	cc:1
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0740 
	cmp4.ge.unc p14,p15=r21, r19			    //47 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN2@gamesx#;;			    //47 	cc:2
 }
 {   .mmi  //R-Addr: 0X0750 
	adds	r18=zy$, sp				    //49 	cc:0
	adds	r11=GGGc$, sp				    //49 	cc:0
	addl	r40=@gprel($SG3917#),gp;;		    //49 	cc:0
 }
 {   .mmi  //R-Addr: 0X0760 
	ld4	r17=[r18];;				    //49 	cc:1
	nop.m	 0
	sxt4	r16=r17;;				    //49 	cc:2
 }
 {   .mii  //R-Addr: 0X0770 
	nop.m	 0
	shl	r15=r16, 2;;				    //49 	cc:3
	add	r10=r11, r15;;				    //49 	cc:4
 }
 {   .mmb  //R-Addr: 0X0780 
	ld4	r41=[r10]				    //49 	cc:5
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //49 	cc:5
 }
 {   .mmb  //R-Addr: 0X0790 
	mov	gp=r39					    //49 	cc:17
	nop.m	 0
	br.cond.sptk.few $LN3@gamesx#;;			    //50 	cc:0
 }
$LN2@gamesx:
 {   .mmi  //R-Addr: 0X07a0 
	adds	r9=islotto$, sp;;			    //51 	cc:0
	ld1	r8=[r9]					    //51 	cc:1
	nop.i	 0;;
 }
 {   .mii  //R-Addr: 0X07b0 
	nop.m	 0
	sxt1	r31=r8;;				    //51 	cc:2
	cmp4.ne.unc p14,p15=r0, r31			    //51 	cc:3
 }
 {   .mmb  //R-Addr: 0X07c0 
	nop.m	 0
	nop.m	 0
  (p14)	br.cond.dptk.few $LN24@gamesx#;;		    //51 	cc:3
 }
 {   .mmb  //R-Addr: 0X07d0 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=rand#;;			    //53 	cc:0
 }
 {   .mmi  //R-Addr: 0X07e0 
	adds	r30=$T4049, sp				    //53 	cc:11
	adds	r29=$T4049, sp				    //53 	cc:11
	adds	r27=ball$, sp				    //53 	cc:11
 }
 {   .mib  //R-Addr: 0X07f0 
	mov	r21=65501				    //53 	cc:11, 0000ffddH
	mov	gp=r39					    //53 	cc:11
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0800 
	st4	[r30]=r8				    //53 	cc:12
	ld4	r28=[r29]				    //53 	cc:12
	addl	r40=@gprel($SG3919#),gp			    //53 	cc:12
 }
 {   .mmb  //R-Addr: 0X0810 
	ld4	r26=[r27]				    //53 	cc:12
	setf.exp f15=r21				    //53 	cc:12
	nop.b	 0;;
 }
 {   .mii  //R-Addr: 0X0820 
	nop.m	 0
	sxt4	r22=r26					    //53 	cc:13
	sxt4	r25=r28;;				    //53 	cc:13
 }
 {   .mmi  //R-Addr: 0X0830 
	setf.sig f12=r25				    //53 	cc:14
	setf.sig f13=r22				    //53 	cc:14
	sub	r21=r0, r22, r21			    //53 	cc:14
 }
 {   .mmi  //R-Addr: 0X0840 
	cmp.eq.unc p15,p0=0, r22;;			    //53 	cc:14
  (p15)	break.m	 1					    //53 	cc:15
	nop.i	 0;;
 }
 {   .mfb  //R-Addr: 0X0850 
	nop.m	 0
	fcvt.xf	f14=f12					    //53 	cc:20
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0860 
	nop.m	 0
	fcvt.xf	f13=f13					    //53 	cc:20
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0870 
	nop.m	 0
	frcpa.s1 f32,p7=f14, f13			    //53 	cc:24
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0880 
	nop.m	 0
  (p7)	fma.s1	f33=f14, f32, f0			    //53 	cc:28
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0890 
	nop.m	 0
  (p7)	fnma.s1	f32=f13, f32, f1			    //53 	cc:28
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X08a0 
	setf.sig f13=r21, f13				    //53 	cc:29
	nop.m	 0
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X08b0 
	nop.m	 0
  (p7)	fma.s1	f14=f32, f32, f15, f14			    //53 	cc:32
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X08c0 
	nop.m	 0
  (p7)	fma.s1	f33=f32, f33, f33			    //53 	cc:32
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X08d0 
	nop.m	 0
  (p7)	fma.s1	f32=f14, f33, f33, f32			    //53 	cc:36
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X08e0 
	nop.m	 0
	fcvt.fx.trunc.s1 f14=f32, f14			    //53 	cc:40
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X08f0 
	nop.m	 0
	xma.l	f32=f14, f13, f12, f32			    //53 	cc:44
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X0900 
	getf.sig r20=f32;;				    //53 	cc:48
	adds	r41=1, r20				    //53 	cc:53
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0910 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //53 	cc:53
 }
 {   .mmi  //R-Addr: 0X0920 
	mov	gp=r39;;				    //53 	cc:64
	nop.m	 0
	nop.i	 0;;
 }
$LN24@gamesx:
 {   .mmi  //R-Addr: 0X0930 
	adds	r19=__$ArrayPad$, sp;;			    //12 	cc:0
	ld8	r40=[r19]				    //12 	cc:1
	nop.i	 0
 }
 {   .mmb  //R-Addr: 0X0940 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=__security_check_cookie#;;	    //12 	cc:1
 }
 {   .mii  //R-Addr: 0X0950 
	mov	gp=r39					    //12 	cc:12
	mov.ret	b0=r36					    //55 	cc:12
	adds	sp=176, sp;;				    //55 	cc:12, 000000b0H
 }
 {   .mii  //R-Addr: 0X0960 
	nop.m	 0
	mov.i	ar.pfs=r37;;				    //55 	cc:13
	mov.i	ar.lc=r38				    //55 	cc:14
 }
 {   .mmb  //R-Addr: 0X0970 
	nop.m	 0
	nop.m	 0
	br.ret.sptk.many b0;;				    //55 	cc:14
 }
// End code for function:
	.endp	gamesx#
	.section	.pdata
$T4056:	data4	@imagerel(numbersx#)
	data4	@imagerel(numbersx#+656)
	data4	@imagerel($T4055#)
	.section	.xdata
$T4055:	data2	03H
	data2	00H
	data4	03H
	string	"\x07"		//R1:prologue size 7
	string	"\xe6\x00"	//P7:pfs_when time 0
	string	"\xb1\x22"	//P3:pfs_gr 34
	string	"\xe0\x01\x02"	//P7:mem_stack_f time 1 size 2
	string	"\xe4\x02"	//P7:rp_when time 2
	string	"\xb0\xa1"	//P3:rp_gr 33
	string	"\x61\x74"	//R3:body size 116
	string	"\x81"		//B1:label_state 1
	string	"\xc0\x04"	//B2:ecount 0 time 4
	string	"\x00\x00\x00\x00\x00\x00\x00" //padding
// Function compile flags: /Odtp
	.section	.text

// Begin code for function: numbersx:
	.proc	numbersx#
	.align 32
x$	= 16
jhe1$	= 20
jhe$	= 24
$T4054	= 28
xrange$	= 32
numbersx: 
// xrange$ = r32
// Output regs: r36-r37
 {   .mmi  //R-Addr: 0X00 
	alloc	r34=1, 3, 2, 0				    //58 	cc:0
	adds	sp=-32, sp				    //58 	cc:0
	mov	r33=b0					    //58 	cc:0
 }
 {   .mmi  //R-Addr: 0X010 
	mov	r35=gp;;				    //58 	cc:0
	ld8.nta	r2=[sp]					    //58 	cc:1
	adds	r31=xrange$, sp;;
 }
 {   .mmi  //R-Addr: 0X020 
	st4	[r31]=r32;;
	adds	r30=jhe$, sp				    //59 	cc:0
	nop.i	 0;;
 }
 {   .mmi  //R-Addr: 0X030 
	st4	[r30]=r0;;				    //59 	cc:1
	adds	r29=jhe1$, sp				    //60 	cc:0
	nop.i	 0;;
 }
 {   .mmi  //R-Addr: 0X040 
	st4	[r29]=r0;;				    //60 	cc:1
	adds	r28=x$, sp				    //62 	cc:0
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X050 
	st4	[r28]=r0				    //62 	cc:1
	nop.m	 0
	br.cond.sptk.few $LN3@numbersx#;;		    //62 	cc:1
 }
$LN2@numbersx:
 {   .mib  //R-Addr: 0X060 
	adds	r27=x$, sp				    //62 	cc:0
	adds	r22=x$, sp				    //62 	cc:0
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X070 
	ld4	r26=[r27];;				    //62 	cc:1
	adds	r25=1, r26				    //62 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X080 
	st4	[r22]=r25				    //62 	cc:3
	nop.m	 0
	nop.b	 0;;
 }
$LN3@numbersx:
 {   .mib  //R-Addr: 0X090 
	adds	r21=x$, sp				    //62 	cc:0
	adds	r19=xrange$, sp				    //62 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0a0 
	ld4	r20=[r21]				    //62 	cc:1
	ld4	r18=[r19]				    //62 	cc:1
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0b0 
	cmp4.ge.unc p14,p15=r20, r18			    //62 	cc:2
	nop.m	 0
  (p14)	br.cond.dptk.few $LN1@numbersx#;;		    //62 	cc:2
 }
 {   .mmb  //R-Addr: 0X0c0 
	nop.m	 0
	nop.m	 0
	br.call.sptk.few b0=rand#;;			    //64 	cc:0
 }
 {   .mmi  //R-Addr: 0X0d0 
	adds	r17=$T4054, sp				    //64 	cc:11
	adds	r16=$T4054, sp				    //64 	cc:11
	mov	r11=10					    //64 	cc:11
 }
 {   .mmi  //R-Addr: 0X0e0 
	mov	r9=65501				    //64 	cc:11, 0000ffddH
	adds	r31=jhe1$, sp				    //64 	cc:11
	mov	gp=r35;;				    //64 	cc:11
 }
 {   .mmi  //R-Addr: 0X0f0 
	st4	[r17]=r8				    //64 	cc:12
	ld4	r15=[r16]				    //64 	cc:12
	cmp.eq.unc p15,p0=0, r11			    //64 	cc:12
 }
 {   .mmi  //R-Addr: 0X0100 
	setf.sig f7=r11;;				    //64 	cc:12
	setf.exp f9=r9					    //64 	cc:13
	sxt4	r10=r15					    //64 	cc:13
 }
 {   .mib  //R-Addr: 0X0110 
	sub	r9=r0, r11, r9				    //64 	cc:13
  (p15)	break.i	 1					    //64 	cc:13
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0120 
	setf.sig f6=r10					    //64 	cc:14
	nop.m	 0
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0130 
	nop.m	 0
	fcvt.xf	f7=f7					    //64 	cc:18
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0140 
	nop.m	 0
	fcvt.xf	f8=f6					    //64 	cc:20
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0150 
	nop.m	 0
	frcpa.s1 f10,p6=f8, f7				    //64 	cc:24
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0160 
	nop.m	 0
  (p6)	fma.s1	f11=f8, f10, f0				    //64 	cc:28
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X0170 
	nop.m	 0
  (p6)	fnma.s1	f10=f7, f10, f1				    //64 	cc:28
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0180 
	setf.sig f7=r9, f7				    //64 	cc:29
	nop.m	 0
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X0190 
	nop.m	 0
  (p6)	fma.s1	f8=f10, f10, f9, f8			    //64 	cc:32
	nop.b	 0
 }
 {   .mfb  //R-Addr: 0X01a0 
	nop.m	 0
  (p6)	fma.s1	f11=f10, f11, f11			    //64 	cc:32
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X01b0 
	nop.m	 0
  (p6)	fma.s1	f10=f8, f11, f11, f10			    //64 	cc:36
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X01c0 
	nop.m	 0
	fcvt.fx.trunc.s1 f8=f10, f8			    //64 	cc:40
	nop.b	 0;;
 }
 {   .mfb  //R-Addr: 0X01d0 
	nop.m	 0
	xma.l	f10=f8, f7, f6, f10			    //64 	cc:44
	nop.b	 0;;
 }
 {   .mmi  //R-Addr: 0X01e0 
	getf.sig r8=f10;;				    //64 	cc:48
	st4	[r31]=r8				    //64 	cc:53
	nop.i	 0;;
 }
 {   .mib  //R-Addr: 0X01f0 
	adds	r30=jhe1$, sp				    //65 	cc:0
	addl	r36=@gprel($SG3930#),gp			    //65 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0200 
	ld4	r37=[r30]				    //65 	cc:1
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //65 	cc:1
 }
 {   .mmi  //R-Addr: 0X0210 
	mov	gp=r35;;				    //65 	cc:12
	adds	r29=jhe$, sp				    //66 	cc:0
	adds	r27=jhe1$, sp				    //66 	cc:0
 }
 {   .mmi  //R-Addr: 0X0220 
	adds	r22=jhe$, sp;;				    //66 	cc:0
	ld4	r28=[r29]				    //66 	cc:1
	nop.i	 0
 }
 {   .mmi  //R-Addr: 0X0230 
	ld4	r26=[r27];;				    //66 	cc:1
	add	r25=r28, r26				    //66 	cc:2
	nop.i	 0;;
 }
 {   .mmb  //R-Addr: 0X0240 
	st4	[r22]=r25				    //66 	cc:4
	nop.m	 0
	br.cond.sptk.few $LN2@numbersx#;;		    //67 	cc:0
 }
$LN1@numbersx:
 {   .mib  //R-Addr: 0X0250 
	adds	r21=jhe$, sp				    //68 	cc:0
	addl	r36=@gprel($SG3931#),gp			    //68 	cc:0
	nop.b	 0;;
 }
 {   .mmb  //R-Addr: 0X0260 
	ld4	r37=[r21]				    //68 	cc:1
	nop.m	 0
	br.call.sptk.few b0=printf#;;			    //68 	cc:1
 }
 {   .mmi  //R-Addr: 0X0270 
	mov	gp=r35;;				    //68 	cc:12
	adds	sp=32, sp				    //69 	cc:0
	mov.ret	b0=r33;;				    //69 	cc:0
 }
 {   .mib  //R-Addr: 0X0280 
	nop.m	 0
	mov.i	ar.pfs=r34				    //69 	cc:1
	br.ret.sptk.many b0;;				    //69 	cc:1
 }
// End code for function:
	.endp	numbersx#

// Total code size for all functions: 0X01ce0 bytes (462 bundles)

// END
